#include <stdio.h>
#include <stdint.h>
#include "gb_mem_map.h"
#include "gb_opcodes.h"




struct gb_opcode opcode_table[OPCODE_TABLE_SIZE] = {
    {"NOP",         1, CYCLE_1,                 &opcode_nop        /* , NULL, NULL, NULL*/},
    {"LD BC u16",   3, CYCLE_3,                 &opcode_16_ld      /* , &gb_cpu_reg[GB_REG_BC], &u16_pointer, NULL*/},
    {"LD (BC), A",  1, CYCLE_2,                 &opcode_8_ld       /* , bc_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"INC BC",      1, CYCLE_2,                 &opcode_16_inc     /* , &gb_cpu_reg[GB_REG_BC], NULL, NULL*/},
    {"INC B",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"DEC B",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"LD B, u8",    2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &u8_pointer, NULL*/},
    {"RLCA",        1, CYCLE_1,                 &opcode_rlca       /* , NULL, NULL, NULL*/},
    {"LD (u16),SP", 3, CYCLE_5,                 &opcode_16_add_sp  /* , &u16_pointer, &gb_cpu_reg[GB_REG_SP], NULL*/},
    {"ADD HL,BC",   1, CYCLE_2,                 &opcode_16_add_hl  /* , &gb_cpu_reg[GB_REG_HL], &gb_cpu_reg[GB_REG_BC], NULL*/},
    {"LD A,(BC)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], bc_pointer, NULL*/},
    {"DEC BC",      1, CYCLE_2,                 &opcode_16_dec     /* , &gb_cpu_reg[GB_REG_BC], NULL, NULL*/},
    {"INC C",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"DEC C",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"LD C,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &u8_pointer, NULL*/},
    {"RRCA",        1, CYCLE_1,                 &opcode_rrca       /* , NULL, NULL, NULL*/},
    {"STOP 0",      1, CYCLE_1,                 &opcode_stop       /* , NULL, NULL, NULL*/},
    {"LD DE,u16",   3, CYCLE_3,                 &opcode_16_ld      /* , &gb_cpu_reg[GB_REG_DE], &u16_pointer, NULL*/},
    {"LD (DE),A",   1, CYCLE_2,                 &opcode_8_ld       /* , de_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"INC DE",      1, CYCLE_2,                 &opcode_16_inc     /* , &gb_cpu_reg[GB_REG_DE], NULL, NULL*/},
    {"INC D",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"DEC D",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"LD D,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &u8_pointer, NULL*/},
    {"RLA",         1, CYCLE_1,                 &opcode_rla        /* , NULL, NULL, NULL*/},
    {"JR s8",       2, CYCLE_3,                 &opcode_jr         /* , &s8_pointer, NULL, NULL*/},
    {"ADD HL,DE",   1, CYCLE_2,                 &opcode_16_add_hl  /* , &gb_cpu_reg[GB_REG_HL], &gb_cpu_reg[GB_REG_DE], NULL*/},
    {"LD A,(DE)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], de_pointer, NULL*/},
    {"DEC DE",      1, CYCLE_2,                 &opcode_16_dec     /* , &gb_cpu_reg[GB_REG_DE], NULL, NULL*/},
    {"INC E",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"DEC E",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"LD E,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &u8_pointer, NULL*/},
    {"RRA",         1, CYCLE_1,                 &opcode_rra        /* , NULL, NULL, NULL*/},
    {"JR NZ,s8",    2, ALT_CYCLE_3 | CYCLE_2,   &opcode_jr_cnd     /* , NULL, &s8_pointer, NULL*/},
    {"LD HL,u16",   3, CYCLE_3,                 &opcode_16_ld      /* , &gb_cpu_reg[GB_REG_HL], &u16_pointer, NULL*/},
    {"LD (HL+),A",  1, CYCLE_2,                 &opcode_8_ldi      /* , &hl_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"INC HL",      1, CYCLE_2,                 &opcode_16_inc     /* , &gb_cpu_reg[GB_REG_HL], NULL, NULL*/},
    {"INC H",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"DEC H",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"LD H,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &u8_pointer, NULL*/},
    {"DAA",         1, CYCLE_1,                 &opcode_8_daa      /* , NULL, NULL, NULL*/},
    {"JR Z,s8",     2, ALT_CYCLE_3 | CYCLE_2,   &opcode_jr_cnd     /* , NULL, &s8_pointer, NULL*/},
    {"ADD HL,HL",   1, CYCLE_2,                 &opcode_16_add_hl  /* , &gb_cpu_reg[GB_REG_HL], &gb_cpu_reg[GB_REG_HL], NULL*/},
    {"LD A,(HL+)",  1, CYCLE_2,                 &opcode_8_ldi      /* , &gb_cpu_reg[GB_REG_A], &hl_pointer, NULL*/},
    {"DEC HL",      1, CYCLE_2,                 &opcode_16_dec     /* , &gb_cpu_reg[GB_REG_HL], NULL, NULL*/},
    {"INC L",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"DEC L",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"LD L,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &u8_pointer, NULL*/},
    {"CPL",         1, CYCLE_1,                 &opcode_8_cpl      /* , NULL, NULL, NULL*/},
    {"JR NC,s8",    2, ALT_CYCLE_3 | CYCLE_2,   &opcode_jr_cnd     /* , NULL, &s8_pointer, NULL*/},
    {"LD SP,u16",   3, CYCLE_3,                 &opcode_16_ld      /* , &gb_cpu_reg[GB_REG_SP], &u16_pointer, NULL*/},
    {"LD (HL-),A",  1, CYCLE_2,                 &opcode_8_ldd      /* , &hl_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"INC SP",      1, CYCLE_2,                 &opcode_16_inc     /* , &gb_cpu_reg[GB_REG_SP], NULL, NULL*/},
    {"INC (HL)",    1, CYCLE_3,                 &opcode_8_inc      /* , &hl_pointer, NULL, NULL*/},
    {"DEC (HL)",    1, CYCLE_3,                 &opcode_8_dec      /* , &hl_pointer, NULL, NULL*/},
    {"LD (HL),u8",  2, CYCLE_3,                 &opcode_8_ld       /* , &hl_pointer, &u8_pointer, NULL*/},
    {"SCF",         1, CYCLE_1,                 &opcode_scf        /* , NULL, NULL, NULL*/},
    {"JR C,s8",     2, ALT_CYCLE_3 | CYCLE_2,   &opcode_jr_cnd     /* , NULL, &s8_pointer, NULL*/},
    {"ADD HL,SP",   1, CYCLE_2,                 &opcode_16_add_hl  /* , &gb_cpu_reg[GB_REG_HL], &gb_cpu_reg[GB_REG_SP], NULL*/},
    {"LD A,(HL-)",  1, CYCLE_2,                 &opcode_8_ldd      /* , &gb_cpu_reg[GB_REG_A], &hl_pointer, NULL*/},
    {"DEC SP",      1, CYCLE_2,                 &opcode_16_dec     /* , &gb_cpu_reg[GB_REG_SP], NULL, NULL*/},
    {"INC A",       1, CYCLE_1,                 &opcode_8_inc      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"DEC A",       1, CYCLE_1,                 &opcode_8_dec      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"LD A,u8",     2, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &u8_pointer, NULL*/},
    {"CCF",         1, CYCLE_1,                 &opcode_ccf        /* , NULL, NULL, NULL*/},
    {"LD B,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD B,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD B,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD B,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD B,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD B,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD B,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &hl_pointer, NULL*/},
    {"LD B,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_B], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD C,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_B],, NULL*/},
    {"LD C,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD C,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD C,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD C,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD C,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD C,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &hl_pointer, NULL*/},
    {"LD C,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_C], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD D,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD D,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD D,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD D,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD D,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD D,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD D,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &hl_pointer, NULL*/},
    {"LD D,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_D], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD E,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD E,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD E,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD E,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD E,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD E,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD E,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &hl_pointer, NULL*/},
    {"LD E,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_E], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD H,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD H,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD H,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD H,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD H,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD H,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD H,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &hl_pointer, NULL*/},
    {"LD H,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_H], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD L,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD L,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD L,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD L,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD L,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD L,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD L,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &hl_pointer, NULL*/},
    {"LD L,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_L], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD (HL),B",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD (HL),C",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD (HL),D",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD (HL),E",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD (HL),H",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD (HL),L",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_L], NULL*/},
    {"HALT",        1, CYCLE_1,                 &opcode_halt       /* , NULL, NULL, NULL*/},
    {"LD (HL),A",   1, CYCLE_1,                 &opcode_8_ld       /* , &hl_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"LD A,B",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"LD A,C",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"LD A,D",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"LD A,E",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"LD A,H",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"LD A,L",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"LD A,(HL)",   1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &hl_pointer, NULL*/},
    {"LD A,A",      1, CYCLE_1,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"ADD A,B",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"ADD A,C",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"ADD A,D",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"ADD A,E",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"ADD A,H",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"ADD A,L",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"ADD A,(HL)",  1, CYCLE_2,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &hl_pointer, NULL*/},
    {"ADD A,A",     1, CYCLE_1,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"ADC A,B",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_B], NULL*/},
    {"ADC A,C",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_C], NULL*/},
    {"ADC A,D",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_D], NULL*/},
    {"ADC A,E",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_E], NULL*/},
    {"ADC A,H",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_H], NULL*/},
    {"ADC A,L",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_L], NULL*/},
    {"ADC A,(HL)",  1, CYCLE_2,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &hl_pointer, NULL*/},
    {"ADC A,A",     1, CYCLE_1,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &gb_cpu_reg[GB_REG_A], NULL*/},
    {"SUB B",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"SUB C",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"SUB D",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"SUB E",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"SUB H",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"SUB L",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"SUB (HL)",    1, CYCLE_2,                 &opcode_8_sub      /* , &hl_pointer, NULL, NULL*/},
    {"SUB A",       1, CYCLE_1,                 &opcode_8_sub      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"SBC B",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"SBC C",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"SBC D",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"SBC E",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"SBC H",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"SBC L",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"SBC (HL)",    1, CYCLE_2,                 &opcode_8_sbc      /* , &hl_pointer, NULL, NULL*/},
    {"SBC A",       1, CYCLE_1,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"AND B",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"AND C",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"AND D",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"AND E",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"AND H",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"AND L",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"AND (HL)",    1, CYCLE_2,                 &opcode_8_and      /* , &hl_pointer, NULL, NULL*/},
    {"AND A",       1, CYCLE_1,                 &opcode_8_and      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"XOR B",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_B, NULL, NULL*/},
    {"XOR C",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"XOR D",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"XOR E",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"XOR H",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"XOR L",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"XOR (HL)",    1, CYCLE_2,                 &opcode_8_xor      /* , &hl_pointer, NULL, NULL*/},
    {"XOR A",       1, CYCLE_1,                 &opcode_8_xor      /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"OR B",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"OR C",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"OR D",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"OR E",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"OR H",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"OR L",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"OR (HL)",     1, CYCLE_2,                 &opcode_8_or       /* , &hl_pointer, NULL, NULL*/},
    {"OR A",        1, CYCLE_1,                 &opcode_8_or       /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"CP B",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_B], NULL, NULL*/},
    {"CP C",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_C], NULL, NULL*/},
    {"CP D",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_D], NULL, NULL*/},
    {"CP E",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_E], NULL, NULL*/},
    {"CP H",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_H], NULL, NULL*/},
    {"CP L",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_L], NULL, NULL*/},
    {"CP (HL)",     1, CYCLE_2,                 &opcode_8_cp       /* , &hl_pointer, NULL, NULL*/},
    {"CP A",        1, CYCLE_1,                 &opcode_8_cp       /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"RET NZ",      1, ALT_CYCLE_5 | CYCLE_2,   &opcode_ret_cnd    /* , NULL, NULL, NULL*/},
    {"POP BC",      1, CYCLE_3,                 &opcode_16_pop     /* , NULL, NULL, NULL*/},
    {"JP NZ,u16",   3, ALT_CYCLE_4 | CYCLE_3,   &opcode_jp_cnd     /* , NULL, &u16_pointer, NULL*/},
    {"JP u16",      3, CYCLE_4,                 &opcode_jp         /* , &u16_pointer, NULL, NULL*/},
    {"CALL NZ,u16", 3, ALT_CYCLE_6 | CYCLE_3,   &opcode_call_cnd   /* , NULL, &u16_pointer, NULL*/},
    {"PUSH BC",     1, CYCLE_4,                 &opcode_16_push    /* , NULL, NULL, NULL*/},
    {"ADD A,u8",    2, CYCLE_2,                 &opcode_8_add      /* , &gb_cpu_reg[GB_REG_A], &u8_pointer, NULL*/},
    {"RST 00H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_00H, NULL, NULL*/},
    {"RET Z",       1, ALT_CYCLE_5 | CYCLE_2,   &opcode_ret_cnd    /* , NULL, NULL, NULL*/},
    {"RET",         1, CYCLE_4,                 &opcode_ret        /* , NULL, NULL, NULL*/},
    {"JP Z,u16",    3, ALT_CYCLE_4 | CYCLE_3,   &opcode_jp_cnd     /* , NULL, &u16_pointer, NULL*/},
    {"PREFIX CB",   1, ALT_CYCLE_4 | CYCLE_2,   &opcode_cb_prefix  /* , NULL, NULL, NULL*/},
    {"CALL Z,u16",  3, ALT_CYCLE_6 | CYCLE_3,   &opcode_call_cnd   /* , NULL, &u16_pointer, NULL*/},
    {"CALL u16",    3, CYCLE_6,                 &opcode_call       /* , &u16_pointer, NULL, NULL*/},
    {"ADC A,u8",    2, CYCLE_2,                 &opcode_8_adc      /* , &gb_cpu_reg[GB_REG_A], &u8_pointer, NULL*/},
    {"RST 08H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_08H, NULL, NULL*/},
    {"RET NC",      1, ALT_CYCLE_5 | CYCLE_2,   &opcode_ret_cnd    /* , NULL, NULL, NULL*/},
    {"POP DE",      1, CYCLE_3,                 &opcode_16_pop     /* , NULL, NULL, NULL*/},
    {"JP NC,u16",   3, ALT_CYCLE_4 | CYCLE_3,   &opcode_jp_cnd     /* , NULL, &u16_pointer, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"CALL NC,u16", 3, ALT_CYCLE_6 | CYCLE_3,   &opcode_call_cnd   /* , NULL, &u16_pointer, NULL*/},
    {"PUSH DE",     1, CYCLE_4,                 &opcode_16_push    /* , NULL, NULL, NULL*/},
    {"SUB u8",      2, CYCLE_2,                 &opcode_8_sub      /* , &u8_pointer, NULL, NULL*/},
    {"RST 10H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_10H, NULL, NULL*/},
    {"RET C",       1, ALT_CYCLE_5 | CYCLE_2,   &opcode_ret_cnd    /* , NULL, NULL, NULL*/},
    {"RETI",        1, CYCLE_4,                 &opcode_reti       /* , NULL, NULL, NULL*/},
    {"JP C,u16",    3, ALT_CYCLE_4 | CYCLE_3,   &opcode_jp_cnd     /* , NULL, &u16_pointer, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"CALL C,u16",  3, ALT_CYCLE_6 | CYCLE_3,   &opcode_call_cnd   /* , NULL, &u16_pointer, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"SBC A,u8",    2, CYCLE_2,                 &opcode_8_sbc      /* , &gb_cpu_reg[GB_REG_A], &u8_pointer, NULL*/},
    {"RST 18H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_18H, NULL, NULL*/},
    {"LDH (u8),A",  2, CYCLE_3,                 &opcode_8_ld       /* , &u8_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"POP HL",      1, CYCLE_3,                 &opcode_16_pop     /* , NULL, NULL, NULL*/},
    {"LD (C),A",    1, CYCLE_2,                 &opcode_8_ld       /* , NULL, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"PUSH HL",     1, CYCLE_4,                 &opcode_16_push    /* , NULL, NULL, NULL*/},
    {"AND u8",      2, CYCLE_2,                 &opcode_8_and      /* , &u8_pointer, NULL, NULL*/},
    {"RST 20H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_20H, NULL, NULL*/},
    {"ADD SP,s8",   2, CYCLE_4,                 &opcode_16_add_sp  /* , NULL, &s8_pointer, NULL*/},
    {"JP (HL)",     1, CYCLE_1,                 &opcode_jp_hl      /* , &hl_pointer, NULL, NULL*/},
    {"LD (u16),A",  3, CYCLE_4,                 &opcode_8_ld       /* , &u16_pointer, &gb_cpu_reg[GB_REG_A], NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"XOR u8",      2, CYCLE_2,                 &opcode_8_xor      /* , &u8_pointer, NULL, NULL*/},
    {"RST 28H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_28H, NULL, NULL*/},
    {"LDH A,(u8)",  2, CYCLE_3,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &u8_pointer, NULL*/},
    {"POP AF",      1, CYCLE_3,                 &opcode_16_pop     /* , NULL, NULL, NULL*/},
    {"LD A,(C)",    1, CYCLE_2,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], NULL, NULL*/},
    {"DI",          1, CYCLE_1,                 &opcode_di         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"PUSH AF",     1, CYCLE_4,                 &opcode_16_push    /* , NULL, NULL, NULL*/},
    {"OR u8",       2, CYCLE_2,                 &opcode_8_or       /* , &u8_pointer, NULL, NULL*/},
    {"RST 30H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_30H, NULL, NULL*/},
    {"LD HL,SP+s8", 2, CYCLE_3,                 &opcode_16_ld_offset, /*NULL, NULL, &s8_pointer*/},
    {"LD SP,HL",    1, CYCLE_2,                 &opcode_16_ld      /* , NULL, NULL, NULL*/},
    {"LD A,(u16)",  3, CYCLE_4,                 &opcode_8_ld       /* , &gb_cpu_reg[GB_REG_A], &u16_pointer, NULL*/},
    {"EI",          1, CYCLE_1,                 &opcode_ei         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"NA",          0, 0,                       &opcode_NA         /* , NULL, NULL, NULL*/},
    {"CP u8",       1, CYCLE_2,                 &opcode_8_cp       /* , &u8_pointer, NULL, NULL*/},
    {"RST 38H",     1, CYCLE_4,                 &opcode_rst        /* , &addr_38H, NULL, NULL*/}
};


void print_opcodes(){
    printf("OP - LN - CY : DESC\n");
    for(int i = 0; i < OPCODE_TABLE_SIZE; i++){
        printf("%02X - %02X - %02X : %s\n",i,opcode_table[i].length,opcode_table[i].cycles, opcode_table[i].description);
    }
}